# -*- coding: utf-8 -*-
{
    'name': 'Ausphin Special',
    'version': '0.1',
    'depends': [
        'crm',
        'sale_crm',
        'kanban_draggable',
        'crm_team_sequence',
        'lead_stage_duration',
        'tenureship',
        'visa_history',
        'crm_site',
        'crm_training',
        'hide_field_by_stage',
        'crm_documents',
        'activity_reminder',
    ],
    'external_dependencies': {},
    'author': 'Rainier King, '
              'Odev Solutions',
    'website': 'https://odevsolutions.com',
    'summary': """Special Modifications for Ausphin""",
    'description': """
        Special Modifications for Ausphin
    """,
    'category': 'Special',
    'data': [
        'security/ausphin_special_groups.xml',
        'security/crm_lead_security.sql',
        'security/crm_lead_security.xml',
        'security/crm_team_security.xml',
        'security/crm_stage_security.xml',
        'security/res_users_security.xml',
        'security/sale_order_security.xml',
        'security/sale_order_line_security.xml',
        'data/mail_template_data.xml',
        'data/base_automation_data.xml',
        'views/crm_lead_views.xml',
        'views/crm_team_views.xml',
        'views/crm_stage_views.xml',
        'views/sale_order_views.xml',
        'views/res_users_views.xml',
        'views/sale_order_views.xml',
        'views/res_partner_views.xml',
        'views/account_invoice_views.xml',
        'wizards/crm_lead2opportunity_partner_views.xml',
    ],
    'qweb': [],
    'css': [],
    'images': [],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}